package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAgentOrder;
import org.linlinjava.litemall.db.domain.LitemallAgentOrderExample;

public interface LitemallAgentOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallAgentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAgentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    int insert(LitemallAgentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAgentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    LitemallAgentOrder selectOneByExample(LitemallAgentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    LitemallAgentOrder selectOneByExampleSelective(@Param("example") LitemallAgentOrderExample example, @Param("selective") LitemallAgentOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    List<LitemallAgentOrder> selectByExampleSelective(@Param("example") LitemallAgentOrderExample example, @Param("selective") LitemallAgentOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    List<LitemallAgentOrder> selectByExample(LitemallAgentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    LitemallAgentOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAgentOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    LitemallAgentOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAgentOrder record, @Param("example") LitemallAgentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAgentOrder record, @Param("example") LitemallAgentOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAgentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_agent_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAgentOrder record);
}