package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTickets;
import org.linlinjava.litemall.db.domain.LitemallTicketsExample;

public interface LitemallTicketsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    long countByExample(LitemallTicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    int insert(LitemallTickets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTickets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    LitemallTickets selectOneByExample(LitemallTicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    LitemallTickets selectOneByExampleSelective(@Param("example") LitemallTicketsExample example, @Param("selective") LitemallTickets.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    List<LitemallTickets> selectByExampleSelective(@Param("example") LitemallTicketsExample example, @Param("selective") LitemallTickets.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    List<LitemallTickets> selectByExample(LitemallTicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    LitemallTickets selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTickets.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    LitemallTickets selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTickets record, @Param("example") LitemallTicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTickets record, @Param("example") LitemallTicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTickets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tickets
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTickets record);
}