package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsView;
import org.linlinjava.litemall.db.domain.LitemallGoodsViewExample;

public interface LitemallGoodsViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    LitemallGoodsView selectOneByExample(LitemallGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    LitemallGoodsView selectOneByExampleSelective(@Param("example") LitemallGoodsViewExample example, @Param("selective") LitemallGoodsView.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    List<LitemallGoodsView> selectByExampleSelective(@Param("example") LitemallGoodsViewExample example, @Param("selective") LitemallGoodsView.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    List<LitemallGoodsView> selectByExample(LitemallGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    LitemallGoodsView selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsView.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    LitemallGoodsView selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsView record, @Param("example") LitemallGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsView record, @Param("example") LitemallGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_view
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsView record);
}