package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPlatformView;
import org.linlinjava.litemall.db.domain.LitemallPlatformViewExample;

public interface LitemallPlatformViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    long countByExample(LitemallPlatformViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPlatformViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    int insert(LitemallPlatformView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPlatformView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    LitemallPlatformView selectOneByExample(LitemallPlatformViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    LitemallPlatformView selectOneByExampleSelective(@Param("example") LitemallPlatformViewExample example, @Param("selective") LitemallPlatformView.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    List<LitemallPlatformView> selectByExampleSelective(@Param("example") LitemallPlatformViewExample example, @Param("selective") LitemallPlatformView.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    List<LitemallPlatformView> selectByExample(LitemallPlatformViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    LitemallPlatformView selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPlatformView.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    LitemallPlatformView selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPlatformView record, @Param("example") LitemallPlatformViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPlatformView record, @Param("example") LitemallPlatformViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPlatformView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform_view
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPlatformView record);
}